language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - liblog4cxx10-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-date-time-dev
        - libboost-dev
        - libboost-system-dev
        - libboost-test-dev
        - libboost-thread-dev
        - libzmq3-dev
        - libpcap-dev
        - libboost-regex-dev
    env: HDF5_ROOT=$HOME/hdf5-1.10.1 INSTALL_PREFIX=$HOME/install_prefix ODIN_PREFIX=$HOME/odin-data-systemtest
    before-install:
    - bash .travis-install-hdf5.sh
    - bash .travis-install-log4cxx.sh
    - bash .travis-install-odin.sh
install:
- mkdir -p build
- mkdir -p $INSTALL_PREFIX
- cd build;
- cmake -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DLOG4CXX_ROOT_DIR=$HOME/$LOG4CXX -DODINDATA_ROOT_DIR=$ODIN_PREFIX ../data;
- cmake --build . --target install;
- cd ..
script:
- ./${ODIN_PREFIX}/bin/odinDataTest --ini=${INSTALL_PREFIX}/test_config/excalibur.ini
after_success:
- coveralls
notifications:
  slack:
    secure: kKmPRPxIkhTf5wQR+KYtmid7FHD29OwQMdYYyMNzUdVHk4QJZ4SW32Jt5IHemY4V/PgTRmTvSwDDsjYV3y9rExdCAQgKfaLSLdRkZFR7FIGNWRCJ2GoCSB8I/gT9HfayoLaOGiE1EJG4S3WMdqShUNgEdraTuZ8byzOM50qKyKGeYMVGxo7DI+AmgSznEKQ6zWP4nqZuY7S0ns8hf42s0TQUsnfPFpfKfZtpxtl1cTbM2P4g8iKdhNPgBAfZis8/o2w+pZEmKoTeAUepkt/7V6H0TD8OjHEWpC4n0TydU/BKu/SgSqp/t6hFUTr7V5zN265I4dLwWz/mcTO1NV17f24DIiGPOemaG45xqtbj400X4xEUpvTjgchKIE1AAZGJnDdybGh15AvmCg5/jYQPL9pDO8JCEqfLUdUYQqKZpUumwwFOl7Ck1ESuHmb+pld+2xPa8sK2pdclDL+9lrbzvF2BfQ1bdrn4RU5LyYaYa9/l4Tbjn5z3ubpMQorslD7GFy4X6fu5R9VTfxxN8DS51j889lKQ7h5ZODz8Ohhock3OeqHXZUKygJWXQR9Q2xXdr3nFVleOzY6/2oIIwfmh/95FOIBC2z2CPUjNHp5gGsVMyFQh9fGnriHFb5nhn1aVMR9QzwVjVn7hPXwoXfCn2q4nF2OV2GAFGCEiwQZEDR4=
